language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4
    - php: nightly

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

# we need sudo to install apache
sudo: required

# services we need to start
services:
  - mysql

before_install:
  # update apt
  - travis_retry sudo apt-get update
  # use node 12
  - nvm install 12
  - nvm use 12

install:
  # install apache
  - travis_retry sudo apt-get install apache2 libapache2-mod-fastcgi
  # add composer to PATH
  - export PATH="$HOME/.composer/vendor/bin:./vendor/bin:$PATH"
  # install php dependancies
  - travis_retry composer install -o --no-interaction
  # install node dependancies
  - npm install

before_script:
  # fetch all tags
  - git fetch --tags
  # create database
  - travis_retry mysql -e "CREATE DATABASE symphony_test CHARACTER SET = 'utf8mb4' COLLATE = 'utf8mb4_unicode_ci';"
  # install and configure apache
  - ./tests/ci/travis-configure-apache.sh

script:
  # run unit tests
  - npm test
  # clean up unit tests
  - php tests/shutdown.php
  # install symphony
  - ./tests/ci/travis-install-symphony.sh
  # run integration tests
  - npm run integration
  # run phpstan
  - npm run stan
  # run bcc
  #- npm run bcc

after_success:
  # merge code coverage reports
  - phpcov merge . --clover coverage.xml
  # send it to codecov
  - bash <(curl -s https://codecov.io/bash)

cache:
  npm: true
  composer: true
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor
